### ISSUE TITLE
Vulkan development files not present (vulkan/vk_layer_dispatch_table.h) ? VK Loader 1.2.145

### ISSUE THREAD

**Issue by VortexAcherontic** [aejsmith/vkdevicechooser#11]
Hey there I was about to build an RPM for openSUSE out of your source.

However meson complains about vk_layer_dispatch_table.h been missing.

I validated several things and still I am unsure if the openSUSE vulkan developemnt and header packages are just missing this file or if the meson script is wrong here maybe because that header file got removed by the Vulkan devs themselves in the most recent version?

I found a package on the build service which has a packed source archive of Vulkan Loader 1.2.145 which contains this file but it seems not to be present in the final RPM which is build out of this and therefore not "installed" in the include directory.

According to the spec file it builds vulkan-devel and libvulkan1 but no trace of the header file anywhere in those rpms but in the archive.

So my question is if this package was build upon an older/newer version (at this point I found Vulkan Loader 1.2.148 in the Khronos GitHub repo) of Vulkan and recent/older versions do/did not have this header or if I need to contact the package maintainer of the vulkan-loader packages and point him to the missing file.

Keep in mind that my Vulkan knowledge is very minimal ^^"

**Comment by aejsmith** [comment]
On Fedora the header is provided by `vulkan-validation-layers-devel` and on Ubuntu it's `vulkan-validationlayers-dev`. Is there an equivalent on openSUSE?

**Comment by VortexAcherontic** [comment]
A yes I opened an issue. 😄 

Uhm yes it is but I found out that it is in fact missing that file and already created a bugreport in opensuses bugzilla.

I close this here now since you did everything just right :)
