### ISSUE TITLE
Meson fails to find vk_layer_dispatch_table.h

### ISSUE THREAD

**Issue by xolophreny** [aejsmith/vkdevicechooser#12]
Trying to build on Void Linux, installed packages `vulkan-loader`, `Vulkan-Headers`, `Vulkan-ValidationLayers`, file `/usr/include/vk_layer_dispatch_table.h` is present, yet Meson is unable to find it for some reason. Vulkan version 1.2.141

**Comment by xolophreny** [comment]
Aha, should be `/usr/include/vulkan/vk_layer_dispatch_table.h`... Maybe a packaging issue

**Comment by yuanzhi1209** [comment]
解决 了吗
