### ISSUE TITLE
Not Working with Refres2025 --force-vulkan

### ISSUE THREAD

**Issue by plasticbomb1986** [aejsmith/vkdevicechooser#2]
Used commands:
./Refresh2025.x86_64 --force-vulkan ENABLE_DEVICE_CHOOSER_LAYER=1 VULKAN_DEVICE_INDEX=1 vulkaninfo
./Refresh2025.x86_64 --force-vulkan ENABLE_DEVICE_CHOOSER_LAYER=1 VULKAN_DEVICE_INDEX=0 vulkaninfo

I have two VEGA64 in my PC running Manjaro KDE, [vulkaninfo pastebin](https://pastebin.com/Gz1mffRM). 

Plus i just tried to run RUST linux native, same result. Both running on the second VEGA what isnt connected to any display.
Same with Subnautica and Subnautica Below Zero.

**Comment by aejsmith** [comment]
The commands are not quite right. You need to put the environment variables before the command you are trying to run, like this:
`ENABLE_DEVICE_CHOOSER_LAYER=1 VULKAN_DEVICE_INDEX=1 ./Refresh2025.x86_64 --force-vulkan`
