### ISSUE TITLE
Which License is this code under?

### ISSUE THREAD

**Issue by Gerdoch** [aejsmith/vkdevicechooser#3]
I use vkdevicechooser daily for gaming on my laptop, and I'm looking at packaging your project up for the Archlinux AUR since I find it really useful and think others might too.  However, I do not want to do so if the license for the code does permit doing such.  What open-source license (if any) applies to this software?  Do you mind if it is packaged for the Arch AUR?

**Comment by aejsmith** [comment]
Sorry, didn't notice this issue until now. I've added a license now (MIT). Feel free to package it!

**Comment by VorpalQ** [comment]
Thanks!  I've gone ahead and packaged it up for the AUR at https://aur.archlinux.org/packages/vkdevicechooser/ just FYI
